apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: cluster-template
  title: New Cluster Template
  description: Create a new Cluster via Rancher API
  tags:
    - recommended
spec:
  owner: backstage/techdocs-core
  type: documentation

  parameters:
    - title: Fill in some steps
      required:
        - name
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          ui:field: EntityNamePicker
          ui:autofocus: true
  steps:
    - id: fetch
      name: Template Docs Skeleton
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.name }}
          description: ${{ parameters.name }}
          destination: ${{ parameters.name }}
          owner: ${{ parameters.name }}

  output:
    links:
      - title: Repository
        url: http://google.de
  # This template is meant to be used on top of an existing template.
  # By adding the following and fetching from an absolute URL you can
  # add in the docs template
 
